'use strict';
const COURSE_KEY='isa-course-maker-v1',GRID=20;
const pieces={block:{name:'Bloco',w:160,h:30},ground:{name:'Chão',w:320,h:160},up:{name:'Rampa ↗',w:200,h:100},down:{name:'Rampa ↘',w:200,h:100},moving:{name:'Plataforma móvel',w:160,h:30},star:{name:'Estrela',w:30,h:30},pod:{name:'Cápsula',w:44,h:44},beetle:{name:'Besouro',w:44,h:44},mushroom:{name:'Cogumelo',w:44,h:44},scorpion:{name:'Escorpião',w:44,h:44},scarab:{name:'Escaravelho',w:44,h:44},bat:{name:'Morcego',w:44,h:44},ghost:{name:'Fantasma',w:44,h:44},pad:{name:'Placa da dupla',w:65,h:20},spawn:{name:'Início',w:32,h:66},goal:{name:'Portal',w:80,h:150}};
let courseDoc=null,editTool='select',editPan=0,selected=-1,drag=null,history=[],future=[];
const ec=$('maker-canvas'),ex=ec.getContext('2d');
function blankCourse(){return{version:1,title:'Minha aventura',theme:0,width:4140,cooperative:false,objective:'exit',target:8,objects:[{type:'ground',x:0,y:570,w:1000,h:160},{type:'ground',x:1120,y:570,w:1400,h:160},{type:'ground',x:2640,y:570,w:1500,h:160},{type:'spawn',x:100,y:500,w:32,h:66},{type:'goal',x:3980,y:490,w:80,h:150},{type:'up',x:300,y:470,w:200,h:100},{type:'down',x:500,y:470,w:200,h:100},...Array.from({length:12},(_,i)=>({type:'star',x:200+i*290,y:490,w:30,h:30})),{type:'beetle',x:830,y:526,w:44,h:44}]};}
function copy(v){return JSON.parse(JSON.stringify(v));}
function remember(){history.push(copy(courseDoc));if(history.length>40)history.shift();future=[];}
function editorStatus(message){$('maker-status').textContent=message;}
function openMaker(){if(!ready){toast('Aguarde as imagens terminarem de carregar.');return;}courseRun=null;buddy=null;buddyKeys={};keys={};pressed={};if(!courseDoc)courseDoc=blankCourse();mode='editor';window.RockAudio?.pause();['start-screen','hud','objective','power-hud','combat-hud','weather-badge','boss-hud','dialogue','cinema','touch','modal','course-exit','duo-touch'].forEach(id=>show(id,false));show('maker');syncMaker();}
function syncMaker(){ $('maker-title').value=courseDoc.title;$('maker-theme').value=courseDoc.theme;$('maker-mode').value=courseDoc.cooperative?'coop':'solo';$('maker-objective').value=courseDoc.objective;$('maker-target').value=courseDoc.target;$('maker-pan').max=courseDoc.width-1280;$('maker-pan').value=editPan;syncProperties();}
function syncProperties(){const o=courseDoc.objects[selected];$('piece-properties').classList.toggle('hidden',!o);if(!o)return;$('piece-name').textContent=pieces[o.type].name;for(const k of ['x','y','w','h'])$('piece-'+k).value=Math.round(o[k]);}
function validCourse(raw){if(!raw||raw.version!==1||!Array.isArray(raw.objects)||raw.objects.length>240)throw Error('Use um mapa do Course Maker com até 240 peças.');const out={version:1,title:String(raw.title||'Minha aventura').slice(0,45),theme:clamp(Math.floor(Number(raw.theme)||0),0,5),width:4140,cooperative:raw.cooperative===true,objective:['exit','stars','enemies','pads'].includes(raw.objective)?raw.objective:'exit',target:clamp(Math.floor(Number(raw.target)||1),1,99),objects:[]};for(const o of raw.objects){if(!pieces[o.type])throw Error('O mapa contém uma peça desconhecida.');const n={type:o.type};for(const k of ['x','y','w','h']){if(!Number.isFinite(o[k]))throw Error('O mapa possui coordenadas inválidas.');n[k]=o[k];}n.w=clamp(n.w,20,1400);n.h=clamp(n.h,20,220);n.x=clamp(n.x,0,4140-n.w);n.y=clamp(n.y,0,680);out.objects.push(n);}return out;}
function validatePlayable(d){const spawn=d.objects.filter(o=>o.type==='spawn'),goals=d.objects.filter(o=>o.type==='goal');if(spawn.length!==1||goals.length!==1)return 'A fase precisa de exatamente um início e um portal.';if(!d.objects.some(o=>['block','ground','up','down','moving'].includes(o.type)))return 'Coloque pelo menos um terreno ou plataforma.';if(d.objective==='stars'&&d.objects.filter(o=>o.type==='star').length+d.objects.filter(o=>o.type==='pod').length*3<d.target)return 'Adicione estrelas suficientes para cumprir o objetivo.';if(d.objective==='enemies'&&d.objects.filter(o=>['beetle','mushroom','scorpion','scarab','bat','ghost'].includes(o.type)).length<d.target)return 'Adicione inimigos suficientes para cumprir o objetivo.';if(d.objective==='pads'&&(!d.cooperative||d.objects.filter(o=>o.type==='pad').length<2))return 'Ative a dupla e coloque pelo menos duas placas.';return '';}
function testCourse(){const error=validatePlayable(courseDoc);if(error){editorStatus(error);return;}courseRun=copy(courseDoc);courseRun.goal=courseRun.objects.find(o=>o.type==='goal');courseCollected=0;courseKills=0;coursePassed=false;const n=courseRun.theme;newLevel(n);mode='play';window.RockAudio?.select(n);if(!soundTouched&&muted)setSound();show('maker',false);show('course-exit');show('duo-touch',courseRun.cooperative);show('dialogue',false);
 platforms=[];gems=[];enemies=[];pods=[];resonators=[];coursePads=[];const terrain=['block','ground','up','down','moving'],creatures=['beetle','mushroom','scorpion','scarab','bat','ghost'];
 for(const o of courseRun.objects){if(terrain.includes(o.type))platforms.push({x:o.x,y:o.y,w:o.w,h:o.h,bx:o.x,by:o.y,ground:o.type==='ground',dx:0,dy:0,slope:o.type==='up'?'up':o.type==='down'?'down':null,axis:o.type==='moving'?'x':null,amp:35,speed:1,phase:0});if(o.type==='star')gems.push({x:o.x+15,y:o.y+15,got:false,phase:o.x});if(o.type==='pod')pods.push({x:o.x+22,y:o.y+22,opened:false});if(o.type==='pad')coursePads.push({x:o.x,y:o.y,w:o.w,h:o.h,active:false,held:0});if(creatures.includes(o.type))enemies.push({type:o.type,x:o.x,y:o.y,baseY:o.y,min:Math.max(0,o.x-90),max:Math.min(courseRun.width-44,o.x+90),w:44,h:44,dir:-1,dead:false,speed:48,phase:0,clock:0,charge:0,stun:0,deathLife:0});}
 const start=courseRun.objects.find(o=>o.type==='spawn');player.x=start.x;player.y=start.y;checkpoint=start.x;player.ground=false;player.support=null;player.vx=player.vy=0;initDogPath();gate.open=true;item.got=true;boss.disabled=true;boss.defeated=true;ingredients=[n];starEnergy=0;mountReady=false;score=0;show('boss-hud',false);if(courseRun.cooperative)buddy={x:start.x+55,y:start.y,w:32,h:66,vx:0,vy:0,ground:false,face:1,jumps:0,stride:0,spin:0,cool:0,invuln:0};else buddy=null;buddyKeys={};buddyPressed={};hud();editorStatus('Teste em andamento. Voltar ao editor preserva suas peças.');}
function finishCourse(){if(goalCD>0)return;goalCD=1;if(Math.abs(player.y+33-courseRun.goal.y)>150)return;const objective=courseRun.objective,done=objective==='exit'||objective==='stars'&&courseCollected>=courseRun.target||objective==='enemies'&&courseKills>=courseRun.target||objective==='pads'&&coursePassed;if(!done){toast('Complete o objetivo antes de atravessar o portal.');return;}if(buddy&&Math.abs(buddy.x-player.x)>130){toast('Esperem um pelo outro: a dupla precisa chegar junta.');return;}mode='course-win';window.RockAudio?.pause();modal('FASE CONCLUÍDA',courseRun.title,`Objetivo cumprido${buddy?' em dupla':''}! Vocês coletaram ${courseCollected} estrelas e venceram ${courseKills} inimigos.`,'Voltar ao criador',openMaker);}
function updateCourseObjectives(dt){if(!courseRun)return;let touched=new Set();for(const p of coursePads){const inside=b=>b&&b.ground&&b.x+b.w>p.x&&b.x<p.x+p.w&&Math.abs(b.y+b.h-(p.y+p.h))<25;p.active=!!(inside(player)||inside(buddy));p.held=p.active?p.held+dt:0;if(inside(player))touched.add('p1');if(inside(buddy))touched.add('p2');}if(coursePads.filter(p=>p.held>1).length>=2&&touched.size===2)coursePassed=true;const o=courseRun.objective;$('quest-text').textContent=o==='exit'?'Chegue ao portal'+(buddy?' em dupla':''):o==='stars'?`Estrelas: ${courseCollected}/${courseRun.target}`:o==='enemies'?`Inimigos: ${courseKills}/${courseRun.target}`:coursePassed?'Placas ativadas! Sigam ao portal':'Cada pessoa em uma placa por 1 segundo';$('stage-name').textContent=courseRun.title;$('stage-small').textContent=buddy?'COURSE MAKER · DUPLA':'COURSE MAKER · SOLO';}
function drawCourseObjects(){if(!courseRun)return;for(const p of coursePads){rr(p.x-camera,p.y,p.w,p.h,5,p.active?'#b0ffb8':'#95aac0','#eaffed');label(p.active?'✓':'P1 / P2',p.x+p.w/2-camera,p.y-8,'#ecfff5',11);}if(buddy)label('P1 · ISA',player.x+16-camera,player.y-47,'#ffdf89',12);}
const makerGain=gainStar;gainStar=function(amount=1,countScore=true){if(courseRun&&countScore)courseCollected+=amount;makerGain(amount,countScore);};
const makerDefeat=defeatEnemy;defeatEnemy=function(e,source='spin'){if(courseRun&&!e.dead)courseKills++;makerDefeat(e,source);};
function makerPoint(e){const r=ec.getBoundingClientRect();return{x:clamp(Math.round(((e.clientX-r.left)/r.width*1280+editPan)/GRID)*GRID,0,4120),y:clamp(Math.round((e.clientY-r.top)/r.height*720/GRID)*GRID,0,660)};}
function pick(p){for(let i=courseDoc.objects.length-1;i>=0;i--){const o=courseDoc.objects[i];if(p.x>=o.x-10&&p.x<=o.x+o.w+10&&p.y>=o.y-10&&p.y<=o.y+o.h+10)return i;}return -1;}
ec.onpointerdown=e=>{if(mode!=='editor')return;e.preventDefault();ec.setPointerCapture(e.pointerId);const p=makerPoint(e);if(editTool==='erase'){const i=pick(p);if(i>=0){remember();courseDoc.objects.splice(i,1);selected=-1;syncProperties();}return;}if(editTool==='select'){selected=pick(p);if(selected>=0){remember();const o=courseDoc.objects[selected];drag={id:e.pointerId,dx:p.x-o.x,dy:p.y-o.y};}syncProperties();return;}if(courseDoc.objects.length>=240){editorStatus('Limite de 240 peças atingido.');return;}remember();const spec=pieces[editTool];if(['spawn','goal'].includes(editTool))courseDoc.objects=courseDoc.objects.filter(o=>o.type!==editTool);courseDoc.objects.push({type:editTool,x:clamp(p.x,0,4140-spec.w),y:p.y,w:spec.w,h:spec.h});selected=courseDoc.objects.length-1;drag={id:e.pointerId,dx:0,dy:0};syncProperties();};
ec.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const p=makerPoint(e),o=courseDoc.objects[selected];o.x=clamp(p.x-drag.dx,0,4140-o.w);o.y=clamp(p.y-drag.dy,0,660);syncProperties();};ec.onpointerup=ec.onpointercancel=ec.onlostpointercapture=()=>drag=null;
function drawEditor(){ctx.fillStyle='#122d3c';ctx.fillRect(0,0,W,H);if(!courseDoc)return;const bg=assets[worlds[courseDoc.theme].bg];ex.clearRect(0,0,1280,720);if(bg)ex.drawImage(bg,0,0,1280,720);ex.fillStyle='#102a3c77';ex.fillRect(0,0,1280,720);ex.strokeStyle='#d2efff22';ex.lineWidth=1;ex.beginPath();for(let x=-editPan%40;x<1280;x+=40){ex.moveTo(x,0);ex.lineTo(x,720);}for(let y=0;y<720;y+=40){ex.moveTo(0,y);ex.lineTo(1280,y);}ex.stroke();
 for(let i=0;i<courseDoc.objects.length;i++){const o=courseDoc.objects[i],x=o.x-editPan;if(x+o.w<0||x>1280)continue;ex.save();if(['ground','block','moving'].includes(o.type)){ex.fillStyle=worlds[courseDoc.theme].rock;ex.fillRect(x,o.y,o.w,o.h);ex.fillStyle=worlds[courseDoc.theme].top;ex.fillRect(x,o.y,o.w,8);if(o.type==='moving'){ex.fillStyle='#fff';ex.font='bold 20px sans-serif';ex.fillText('↔',x+o.w/2-10,o.y+25);}}
 else if(o.type==='up'||o.type==='down'){ex.fillStyle=worlds[courseDoc.theme].top;ex.beginPath();ex.moveTo(x,o.y+(o.type==='up'?o.h:0));ex.lineTo(x+o.w,o.y+(o.type==='up'?0:o.h));ex.lineTo(x+o.w,o.y+o.h);ex.lineTo(x,o.y+o.h);ex.closePath();ex.fill();}
 else if(['spawn','beetle','mushroom','scorpion','scarab','bat','ghost'].includes(o.type)){const im=assets[o.type==='spawn'?'girl-idle':o.type];if(im){const h=o.type==='spawn'?90:64,w=h*im.width/im.height;ex.drawImage(im,x+o.w/2-w/2,o.y+o.h-h,w,h);}}
 else{ex.fillStyle=o.type==='star'?'#ffe185':o.type==='goal'?'#a6fff1':o.type==='pad'?'#b5caff':'#edbaff';ex.fillRect(x,o.y,o.w,o.h);ex.fillStyle='#143d48';ex.font='bold 18px sans-serif';ex.fillText({star:'★',goal:'SAÍDA',pad:'DUPLA',pod:'★'}[o.type],x+3,o.y+Math.min(o.h-3,24));}
 if(i===selected){ex.strokeStyle='#fff5b1';ex.lineWidth=4;ex.strokeRect(x-3,o.y-3,o.w+6,o.h+6);}ex.restore();}
 ex.fillStyle='#102c3c';ex.fillRect(0,686,1280,34);ex.fillStyle='#d4eeee';ex.font='16px sans-serif';ex.fillText(`Trecho ${Math.round(editPan)}–${Math.round(editPan+1280)} · ${courseDoc.objects.length}/240 peças · ${editTool==='select'?'Arraste para mover':editTool==='erase'?'Toque para apagar':pieces[editTool].name+': toque para colocar'}`,18,708);
}
$('maker-open').onclick=openMaker;$('maker-close').onclick=()=>{show('maker',false);menu();};$('maker-test').onclick=testCourse;$('course-exit').onclick=openMaker;
$('maker-palette').innerHTML='<button data-piece="select" class="chosen">Mover</button><button data-piece="erase">Apagar</button>'+Object.entries(pieces).map(([k,v])=>`<button data-piece="${k}">${v.name}</button>`).join('');
$('maker-palette').onclick=e=>{const b=e.target.closest('[data-piece]');if(!b)return;editTool=b.dataset.piece;$('maker-palette').querySelectorAll('button').forEach(x=>x.classList.toggle('chosen',x===b));};
$('maker-pan').oninput=e=>editPan=Number(e.target.value);
for(const [id,key,convert] of [['maker-title','title',v=>v.slice(0,45)],['maker-theme','theme',Number],['maker-mode','cooperative',v=>v==='coop'],['maker-objective','objective',v=>v],['maker-target','target',v=>clamp(Math.floor(Number(v)||1),1,99)]])$(id).onchange=e=>{remember();courseDoc[key]=convert(e.target.value);syncMaker();};
for(const k of ['x','y','w','h'])$('piece-'+k).onchange=e=>{const o=courseDoc.objects[selected];if(!o)return;remember();const v=Number(e.target.value);if(!Number.isFinite(v))return;o[k]=clamp(Math.round(v/20)*20,k==='w'||k==='h'?20:0,k==='x'?4140-o.w:k==='y'?660:k==='w'?1400:220);o.x=Math.min(o.x,4140-o.w);syncProperties();};
$('piece-delete').onclick=()=>{if(selected<0)return;remember();courseDoc.objects.splice(selected,1);selected=-1;syncProperties();};
$('maker-undo').onclick=()=>{if(!history.length)return;future.push(copy(courseDoc));courseDoc=history.pop();selected=-1;syncMaker();};$('maker-redo').onclick=()=>{if(!future.length)return;history.push(copy(courseDoc));courseDoc=future.pop();selected=-1;syncMaker();};
$('maker-new').onclick=()=>{remember();courseDoc=blankCourse();selected=-1;editPan=0;syncMaker();editorStatus('Novo mapa. Desfazer recupera a edição anterior.');};
$('maker-save').onclick=()=>{try{localStorage.setItem(COURSE_KEY,JSON.stringify(courseDoc));editorStatus('Mapa salvo neste aparelho. Use Exportar para compartilhar.');}catch{editorStatus('Não foi possível salvar. Use Exportar para guardar o mapa.');}};
$('maker-load').onclick=()=>{try{const s=localStorage.getItem(COURSE_KEY);if(!s){editorStatus('Ainda não existe mapa salvo neste aparelho.');return;}const d=validCourse(JSON.parse(s));remember();courseDoc=d;selected=-1;syncMaker();editorStatus('Mapa carregado.');}catch(e){editorStatus(e.message);}};
$('maker-export').onclick=()=>{const b=new Blob([JSON.stringify(courseDoc,null,2)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='isa-minha-fase.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);editorStatus('Mapa exportado. Outro jogador pode usar Importar.');};
$('maker-import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>200000)throw Error('O mapa deve ter até 200 KB.');const d=validCourse(JSON.parse(await f.text()));remember();courseDoc=d;selected=-1;editPan=0;syncMaker();editorStatus('Mapa importado. Toque em Testar fase.');}catch(err){editorStatus(err.message||'Arquivo inválido.');}e.target.value='';};
document.querySelectorAll('[data-duo]').forEach(b=>{const k=b.dataset.duo;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(mode!=='play')return;if(!buddyKeys[k])buddyPressed[k]=true;buddyKeys[k]=true;};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>buddyKeys[k]=false;});window.addEventListener('blur',()=>{buddyKeys={};buddyPressed={};});
